# Generated by Django 6.0.3 on 2026-03-29 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('is_primary_smc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=8)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=18)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=18)),
                ('position_size_lots', models.DecimalField(decimal_places=4, max_digits=12)),
                ('leverage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('margin_used', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('swap_fee', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pnl_account_currency', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pnl_base_currency', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('account_currency', models.CharField(default='USD', max_length=8)),
                ('base_currency', models.CharField(default='USD', max_length=8)),
                ('risk_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('screenshot_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='market.asset')),
                ('tags', models.ManyToManyField(blank=True, related_name='trades', to='journal.setuptag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeAnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('avg_r_multiple', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gross_loss', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TradeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='journal.trade')),
            ],
        ),
    ]
