# Generated by Django 6.0.3 on 2026-03-29 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8)),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('is_actioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BehaviorMetricDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('avg_leverage', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('swap_cost_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('long_win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('short_win_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('risk_breach_count', models.PositiveIntegerField(default=0)),
                ('overtrade_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'metric_date'), name='uniq_metric_per_user_day')],
            },
        ),
    ]
