# Generated by Django 6.0.3 on 2026-03-29 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('market_type', models.CharField(choices=[('forex', 'Forex'), ('index', 'Index'), ('commodity', 'Commodity'), ('stock', 'Stock'), ('crypto', 'Crypto')], max_length=16)),
                ('broker', models.CharField(max_length=64)),
                ('base_currency', models.CharField(default='USD', max_length=8)),
                ('quote_currency', models.CharField(default='USD', max_length=8)),
                ('default_leverage', models.DecimalField(decimal_places=2, default=20.0, max_digits=8)),
                ('max_leverage', models.DecimalField(decimal_places=2, default=200.0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CFDCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread_points', models.DecimalField(decimal_places=5, max_digits=12)),
                ('overnight_swap_long', models.DecimalField(decimal_places=5, max_digits=12)),
                ('overnight_swap_short', models.DecimalField(decimal_places=5, max_digits=12)),
                ('margin_requirement_percent', models.DecimalField(decimal_places=3, max_digits=6)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='market.asset')),
            ],
        ),
        migrations.CreateModel(
            name='FairValueGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('M1', 'M1'), ('M5', 'M5'), ('M15', 'M15'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1')], max_length=3)),
                ('gap_type', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish')], max_length=8)),
                ('zone_low', models.DecimalField(decimal_places=8, max_digits=18)),
                ('zone_high', models.DecimalField(decimal_places=8, max_digits=18)),
                ('anchor_time', models.DateTimeField()),
                ('strength_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fvg_zones', to='market.asset')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidityZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('M1', 'M1'), ('M5', 'M5'), ('M15', 'M15'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1')], max_length=3)),
                ('side', models.CharField(choices=[('buy_side', 'Buy-side'), ('sell_side', 'Sell-side')], max_length=16)),
                ('level_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('tolerance_points', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('touch_count', models.PositiveIntegerField(default=2)),
                ('strength_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidity_zones', to='market.asset')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('M1', 'M1'), ('M5', 'M5'), ('M15', 'M15'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1')], max_length=3)),
                ('block_type', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish')], max_length=8)),
                ('zone_low', models.DecimalField(decimal_places=8, max_digits=18)),
                ('zone_high', models.DecimalField(decimal_places=8, max_digits=18)),
                ('origin_time', models.DateTimeField()),
                ('strength_score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_blocks', to='market.asset')),
            ],
        ),
        migrations.CreateModel(
            name='SweepEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('M1', 'M1'), ('M5', 'M5'), ('M15', 'M15'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1')], max_length=3)),
                ('direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish')], max_length=8)),
                ('swept_at', models.DateTimeField()),
                ('swept_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('entry_zone_low', models.DecimalField(decimal_places=8, max_digits=18)),
                ('entry_zone_high', models.DecimalField(decimal_places=8, max_digits=18)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sweep_events', to='market.asset')),
                ('liquidity_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sweeps', to='market.liquidityzone')),
            ],
        ),
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('M1', 'M1'), ('M5', 'M5'), ('M15', 'M15'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1')], max_length=3)),
                ('open_time', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=8, max_digits=18)),
                ('high', models.DecimalField(decimal_places=8, max_digits=18)),
                ('low', models.DecimalField(decimal_places=8, max_digits=18)),
                ('close', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=22)),
                ('spread_points', models.DecimalField(decimal_places=5, default=0, max_digits=12)),
                ('bid_close', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('ask_close', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candles', to='market.asset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'timeframe', 'open_time'], name='market_cand_asset_i_7815e4_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'timeframe', 'open_time'), name='uniq_candle_asset_tf_time')],
            },
        ),
        migrations.CreateModel(
            name='DailyBias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('timeframe', models.CharField(choices=[('M1', 'M1'), ('M5', 'M5'), ('M15', 'M15'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1')], default='D1', max_length=3)),
                ('bias', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], max_length=8)),
                ('structure_context', models.JSONField(blank=True, default=dict)),
                ('previous_day_high', models.DecimalField(decimal_places=8, max_digits=18)),
                ('previous_day_low', models.DecimalField(decimal_places=8, max_digits=18)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_biases', to='market.asset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'session_date', 'timeframe'), name='uniq_daily_bias_asset_day_tf')],
            },
        ),
    ]
