# Generated by Django 6.0.3 on 2026-03-29 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=8)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('default_risk_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('max_leverage_limit', models.DecimalField(decimal_places=2, default=20.0, max_digits=8)),
                ('preferred_markets', models.JSONField(blank=True, default=list)),
                ('margin_call_threshold_percent', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('stop_out_threshold_percent', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
