# Generated by Django 6.0.3 on 2026-03-29 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('balance', models.DecimalField(decimal_places=2, default=10000, max_digits=18)),
                ('equity', models.DecimalField(decimal_places=2, default=10000, max_digits=18)),
                ('used_margin', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('free_margin', models.DecimalField(decimal_places=2, default=10000, max_digits=18)),
                ('margin_level_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaperPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=8)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('size_lots', models.DecimalField(decimal_places=4, max_digits=12)),
                ('leverage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('realized_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('swap_accrued', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='paper.paperaccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_positions', to='market.asset')),
            ],
        ),
    ]
